Algoritmo "Maior que 10"
//  
//  
// Disciplina   : [Lógica de Programação com Visualg]
// Professor    : Jailson (JAJA)
// Descrição    : Verifica se um valor é maior que 10.
// Autor(a)     : Vinicius
// Data atual   : 28/09/2024

Var
   valor: inteiro

Inicio
   escreva("Digite um valor: ")
   leia(valor)
   se valor > 10 então
      escreval("É MAIOR QUE 10!")
   senão
      escreval("NÃO É MAIOR QUE 10!")
   fimse
Fimalgoritmo
