Algoritmo "Número Par ou Ímpar"
//  
//  
// Disciplina   : [Lógica de Programação com Visualg]
// Professor    : Jailson (JAJA)
// Descrição    : Verifica se um número é par ou ímpar.
// Autor(a)     : Vinicius
// Data atual   : 28/09/2024

Var
   numero: inteiro

Inicio
   escreva("Digite um número: ")
   leia(numero)
   se numero % 2 = 0 então
      escreval("O número é PAR.")
   senão
      escreval("O número é ÍMPAR.")
   fimse
Fimalgoritmo
