Algoritmo "Positivo ou Negativo"
// Disciplina   : [Lógica de Programação com Visualg]
// Professor    : Jailson (JAJA)
// Descrição    : Verifica se um valor é positivo ou negativo.
// Autor(a)     : Vinicius
// Data atual   : 28/09/2024

Var
   valor: inteiro

Inicio
   escreva("Digite um valor: ")
   leia(valor)
   se valor >= 0 então
      escreval("O valor é positivo.")
   senão
      escreval("O valor é negativo.")
   fimse
Fimalgoritmo
