Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 28/08/2024
Var

lado, area: real


Inicio

   escreva("Digite o valor do lado: ")
   leia(lado)
   area := lado * lado
   escreval("A altura do Quadrado é: ", area)
   
fimalgoritmo



Fimalgoritmo