Algoritmo "Soma Números"
//  
//  
// Disciplina   : [Lógica de Programação com Visualg]
// Professor    : Jailson (JAJA)
// Descrição    : Soma dois números inteiros.
// Autor(a)     : Vinicius
// Data atual   : 28/09/2024

Var
   num1, num2, soma: inteiro

Inicio
   escreva("Digite o primeiro número: ")
   leia(num1)
   escreva("Digite o segundo número: ")
   leia(num2)
   soma <- num1 + num2
   escreval("A soma é: ", soma)
Fimalgoritmo
