Algoritmo "Área Retângulo"
//  
//  
// Disciplina   : [Lógica de Programação com Visualg]
// Professor    : Jailson (JAJA)
// Descrição    : Calcula a área de um retângulo.
// Autor(a)     : Vinicius
// Data atual   : 28/09/2024

Var
   base, altura, area: real

Inicio
   escreva("Digite a base do retângulo: ")
   leia(base)
   escreva("Digite a altura do retângulo: ")
   leia(altura)
   area <- base * altura
   escreval("A área do retângulo é: ", area)
Fimalgoritmo
